from models import Language

VOICE_LANGUAGES = {
    "zh": "Chinese",
    "en": "English",
    "ar": "Arabic",
    "de": "German",
    "fr": "French",
    "es": "Spanish",
    "pt": "Portuguese",
    "id": "Indonesian",
    "it": "Italian",
    "ko": "Korean",
    "ru": "Russian",
    "th": "Thai",
    "vi": "Vietnamese",
    "ja": "Japanese",
    "tr": "Turkish",
    "hi": "Hindi",
    "ms": "Malay",
    "nl": "Dutch",
    "ur": "Urdu",
    "nb": "Norwegian Bokmål",
    "sv": "Swedish",
    "da": "Danish",
    "he": "Hebrew",
    "fi": "Finnish",
    "pl": "Polish",
    "is": "Icelandic",
    "cs": "Czech",
    "fil": "Filipino",
    "fa": "Persian",
}
TEXT_LANGUAGES = {
    "yue": "Cantonese",
    "el": "Greek",
    "af": "Afrikaans",
    "ast": "Asturian",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bs": "Bosnian",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "et": "Estonian",
    "gl": "Galician",
    "gu": "Gujarati",
    "hr": "Croatian",
    "hu": "Hungarian",
    "jv": "Javanese",
    "kk": "Kazakh",
    "kn": "Kannada",
    "ky": "Kyrgyz",
    "lv": "Latvian",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mr": "Marathi",
    "pa": "Punjabi",
    "ro": "Romanian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sw": "Swahili",
    "tg": "Tajik",
    "az": "Azerbaijani",
    "uk": "Ukrainian",
}
LANGUAGES: list[Language] = sorted(
    [Language(code=code, name=name, audio=True) for code, name in VOICE_LANGUAGES.items()]
    + [Language(code=code, name=name, audio=False) for code, name in TEXT_LANGUAGES.items()],
    key=lambda language: language["name"],
)
